[general]
import = [
  #  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/tokyo-night-default.toml",
]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Full"
opacity = 0.9
startup_mode = "Maximized"
dynamic_title = true

[scrolling]
multiplier = 5

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }

size = 15.0

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Beam", blinking = "On" }

[mouse]
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]
